### ISSUE TITLE
Win server and PCNTL

### ISSUE THREAD

**Issue by Gilgalidd** [phpipam/phpipam-agent#17]
Hello,

I've install PHP and dependencies under windows, but the scan fail due to the non support of pcntl.

```
>php index.php discover
--------------------
The following required PHP extensions are missing for phpipam-agent:
  - pcntl
Please recompile PHP to include missing extensions.
--------------------
```

Thanks.

Is it possible to bypass this requirement?

**Comment by Gilgalidd** [comment]
Hello,

The error is due to the PHP version I use. and there is a problem with the list of requirements.
I've change the code to : 
```	
Before:	
		//if ($this->config->nonthreaded === true) {
		//	unset($required_ext['pcntl']);
		//}
After:
		if ($this->config->nonthreaded === true) {
			unset($required_ext[2]);
		}
```
Is it due to the difference between Unix and Windows version of PHP ?

**Comment by phpipam** [comment]
Thanks, fixed.

**Comment by Gilgalidd** [comment]
Still remain a problem with the start() function. It seems to require the pcntl function to create thread.

```
PHP Fatal error:  Uncaught Error: Call to undefined function pcntl_fork() in phpipam-agent-master\functions\classes\class.Thread.php:163
Stack trace:
#0 phpipam-agent-master\functions\classes\class.phpipamAgent.php(857): Thread->start('127.255.255.1')
#1 phpipam-agent-master\functions\classes\class.phpipamAgent.php(657): phpipamAgent->mysql_scan_discover_hosts_ping(Array, Array)
#2 phpipam-agent-master\functions\classes\class.phpipamAgent.php(522): phpipamAgent->mysql_scan_discover_hosts()
#3 phpipam-agent-master\functions\classes\class.phpipamAgent.php(449): phpipamAgent->initialize_mysql()
#4 phpipam-agent-master\index.php(44): phpipamAgent->execute()
#5 {main}
  thrown in phpipam-agent-master\functions\classes\class.Thread.php on line 163
```
