### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpid() 

### ISSUE THREAD

**Issue by telefax** [phpipam/phpipam-agent#37]
I'm getting the following error under php 7.2:

 

```
> # php index.php update
> PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpid() in /opt/ipam-scan-agent/functions/classes/class.Thread.php:205
> Stack trace:
> #0 /opt/ipam-scan-agent/functions/classes/class.phpipamAgent.php(795): Thread->start_fping('192.168.0.0/24')
> #1 /opt/ipam-scan-agent/functions/classes/class.phpipamAgent.php(609): phpipamAgent->mysql_scan_discover_hosts_fping(Array, Array)
> #2 /opt/ipam-scan-agent/functions/classes/class.phpipamAgent.php(518): phpipamAgent->mysql_scan_update_host_statuses()
> #3 /opt/ipam-scan-agent/functions/classes/class.phpipamAgent.php(445): phpipamAgent->initialize_mysql()
> #4 /opt/ipam-scan-agent/index.php(44): phpipamAgent->execute()
> #5 {main}
>   thrown in /opt/ipam-scan-agent/functions/classes/class.Thread.php on line 205
```

Am I missing a dependency?

**Comment by jaronparsons** [comment]
I am having same issue.  Did you ever resolve?

**Comment by jaronparsons** [comment]
You will need to install the posix and ctype php modules I have found.

**Comment by GaryAllan** [comment]
Closing old thread. Please re-open if issue is still present (php-agent code has been updated)
Thank you

**Comment by MikeKall** [comment]
```
PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpid() in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/systemd/src/NotifyS
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(74): gipfl\SystemD\NotifySystemD->setReady()
#1 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(52): Icinga\Module\Director\Daemon\BackgroundDaemon->initialize(
#2 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\Director\Daemon\BackgroundDaemon->
#3 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(182): React\EventLoop\Tick\FutureTickQueue->tick()
#4 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(55): React\EventLoop\StreamSelectLoop->run()
#5 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Direc in /usr/share/icingaweb2/modules/incubator
```
I have the same error. I installed rh-php71-php-ctype, rh-php71-php-soap, rh-php71-php-posix but nothing changed

**Comment by GaryAllan** [comment]
Hi



If the module is enabled, check your php.ini file. The above function is probably blacklisted in the `disable_functions=` line.

InfoSec bods breaking functionality in the default config in the name of security.
